export const USER = {
  name: 'Ekansh Tiwari',
  handle: 'lazyekansh',
  role: 'Full Stack Developer & Builder',
  location: 'Noida, India',
  email: 'lazyekansh@gmail.com',
  github: 'https://github.com/lazyekansh',
  telegram: 'https://t.me/lazyekansh',
  instagram: 'https://instagram.com/lazyekansh',
  shortBio: 'Ekansh Tiwari, also known online as lazyekansh or ek4nsh, is a young developer from Noida, India, born on 26 November 2009. I build tools, automation systems, and platforms with a strong focus on OSINT, AI systems, and developer utilities. I am the creator of projects like osint.ek4nsh.in and EheniasAI, an AI platform designed for aspirants. Despite being only 16 years old, I have already developed multiple APIs, bots, and web applications. Alongside technology, I am also a district level tennis player and I have a strong interest in chess and problem solving.',
}

export const BIO = {
  headline: "I am Ekansh, a 16-year-old full stack developer obsessed with how the internet works.",
  paragraphs: [
    "I started coding because I wanted to understand the internet, not just use it. That curiosity turned into building real tools: OSINT systems, Telegram bots, AI-powered study platforms, and lookup APIs that people actually use.",
    "Right now I am juggling JEE prep alongside building EheniasAI for fellow aspirants and shipping whatever I can think of with React, Next.js, and Python. I go by lazyekansh everywhere, which is ironic because I genuinely do not stop building.",
    "Outside of code I am a district-level tennis player, a daily chess puzzle solver (Rapid: 1613, Blitz: 1358), and a manga reader. I believe the same pattern recognition that helps you find a fork in chess is what helps you debug a race condition at 2am.",
    "I am interested in OSINT, AI systems, and web infrastructure, anything that sits at the intersection of technology and the real world. If you are building something in that space, I would love to talk.",
  ],
  facts: [
    { label: 'Age', value: '16' },
    { label: 'Location', value: 'Noida, India' },
    { label: 'Chess Rapid', value: '1613' },
    { label: 'Chess Blitz', value: '1358' },
    { label: 'Tennis', value: 'District Level' },
    { label: 'Status', value: 'JEE + Building' },
  ],
  interests: [
    { icon: 'chess', title: 'Chess', sub: 'Rapid 1613 / Blitz 1358 / Daily puzzles' },
    { icon: 'tennis', title: 'Tennis', sub: 'District-level player' },
    { icon: 'book', title: 'Manga', sub: 'Daily reader' },
    { icon: 'art', title: '3D / Blender', sub: 'Exploring digital art' },
  ],
}

export const PROJECTS = [
  {
    id: 'osint-tool',
    title: 'OSINT Tool',
    tagline: 'Digital reconnaissance platform.',
    desc: 'Multi-source intelligence tool for number lookups, identity resolution, and API aggregation with primary/fallback architecture.',
    longDesc: "The OSINT Tool is my most serious infrastructure project. It aggregates data from multiple sources to help gather intelligence quickly, handling mobile number lookups, cross-platform identity resolution, and data aggregation from several APIs. The primary/fallback architecture means it never goes down even if one source fails.",
    tags: ['Next.js', 'Node.js', 'Python', 'APIs'],
    link: 'https://osint.ek4nsh.in',
    accent: '#a855f7',
    gradientFrom: 'rgba(168,85,247,0.15)',
    gradientTo: 'rgba(109,40,217,0.05)',
    category: 'Infrastructure',
    year: '2024',
    features: [
      'Multi-source data aggregation with failover',
      'Mobile number intelligence lookup',
      'API key protection and rate limiting',
      'Clean JSON response architecture',
    ],
    tech: ['Next.js', 'Node.js', 'Python', 'Vercel', 'REST APIs'],
    containerClassName: 'md:col-span-2 md:row-span-2',
  },
  {
    id: 'ehenias',
    title: 'EheniasAI',
    tagline: 'Academic OS for JEE/NEET.',
    desc: 'AI-powered study platform with Zen Focus Mode, smart scheduling, and contextual guidance for competitive exam prep.',
    longDesc: "EheniasAI is built for JEE and NEET aspirants drowning in material. It is not just a chatbot, it is an academic operating system with focus modes, study scheduling, and AI-driven progress tracking. I built it because I am living the problem myself.",
    tags: ['React', 'Firebase', 'AI'],
    link: 'https://ehenias.vercel.app',
    accent: '#06b6d4',
    gradientFrom: 'rgba(6,182,212,0.15)',
    gradientTo: 'rgba(14,116,144,0.05)',
    category: 'AI Product',
    year: '2024',
    features: [
      'Zen Focus Mode for distraction-free study',
      'AI-driven study scheduling',
      'Contextual JEE/NEET guidance',
      'Progress tracking and analytics',
    ],
    tech: ['React', 'Firebase', 'OpenAI API', 'Tailwind'],
    containerClassName: 'md:col-span-3',
  },
  {
    id: 'lazy-chess',
    title: 'Lazy Chess',
    tagline: 'Multiplayer chess with Stockfish AI.',
    desc: 'Real-time multiplayer chess with Stockfish integration, adjustable difficulty, and live Socket.io moves.',
    longDesc: "Lazy Chess is a fully functional multiplayer chess platform. Play against Stockfish at adjustable difficulty or challenge another player in real-time. I built this to combine two things I love, chess and programming.",
    tags: ['Socket.io', 'React', 'Chess.js'],
    link: 'https://chess-lazyekansh.vercel.app',
    accent: '#eab308',
    gradientFrom: 'rgba(234,179,8,0.15)',
    gradientTo: 'rgba(161,98,7,0.05)',
    category: 'Game',
    year: '2024',
    features: [
      'Real-time multiplayer via Socket.io',
      'Stockfish AI at multiple difficulty levels',
      'Full chess rules with move validation',
      'Move history and board analysis',
    ],
    tech: ['React', 'Socket.io', 'Chess.js', 'Stockfish WASM'],
    containerClassName: 'md:col-span-2',
  },
  {
    id: 'lazygram',
    title: 'Lazygram',
    tagline: 'Pixel-perfect Instagram clone.',
    desc: 'Full-featured social platform with Stories, Feed, real-time updates, and Firebase auth.',
    longDesc: "Lazygram started as a UI challenge, to rebuild Instagram pixel-perfectly. It became a full-stack project with real auth, image uploads, a live feed, Stories, and Redux global state. Everything you would expect from a social app.",
    tags: ['Next.js', 'Redux', 'Firebase'],
    link: 'https://lazygram.vercel.app',
    accent: '#ec4899',
    gradientFrom: 'rgba(236,72,153,0.15)',
    gradientTo: 'rgba(157,23,77,0.05)',
    category: 'Full Stack',
    year: '2023',
    features: [
      'Stories and Feed with real-time updates',
      'Firebase auth and image uploads',
      'Redux for global state management',
      'Responsive and pixel-perfect UI',
    ],
    tech: ['Next.js', 'Redux', 'Firebase', 'Tailwind'],
    containerClassName: 'md:col-span-3',
  },
  {
    id: 'skycast',
    title: 'SkyCast',
    tagline: 'Weather app with adaptive UI.',
    desc: 'Weather app that shifts its entire color palette based on current conditions: rain, sun, storm.',
    longDesc: "SkyCast dynamically changes its entire color palette and UI based on the current weather condition. Sunny gets warm yellows, rain gets blues and grays, storms get dark dramatic themes. Uses the OpenWeather API and browser geolocation.",
    tags: ['JavaScript', 'OpenWeather API'],
    link: 'https://skycast-le.vercel.app',
    accent: '#60a5fa',
    gradientFrom: 'rgba(96,165,250,0.15)',
    gradientTo: 'rgba(29,78,216,0.05)',
    category: 'Frontend',
    year: '2023',
    features: [
      'Dynamic theme based on weather condition',
      'Browser geolocation',
      '7-day forecast',
      'Animated weather icons',
    ],
    tech: ['Vanilla JS', 'OpenWeather API', 'CSS Animations'],
    containerClassName: 'md:col-span-2',
  },
  {
    id: 'examly',
    title: 'Examly',
    tagline: 'Rapid-fire quiz for JEE/NEET.',
    desc: 'Timed quiz platform for competitive exam aspirants with scoring, analytics, and subject filtering.',
    longDesc: "Examly is a rapid-fire quiz platform built for JEE and NEET prep. Students can filter by subject, set a time limit, and get instant feedback with explanations. The scoring system mirrors actual competitive exam patterns.",
    tags: ['Vanilla JS', 'Logic'],
    link: 'https://NeuroQuiz-le.vercel.app',
    accent: '#22c55e',
    gradientFrom: 'rgba(34,197,94,0.15)',
    gradientTo: 'rgba(20,83,45,0.05)',
    category: 'EdTech',
    year: '2023',
    features: [
      'Subject-filtered question banks',
      'Timed exam simulation',
      'Instant feedback with explanations',
      'Performance analytics',
    ],
    tech: ['Vanilla JS', 'HTML', 'CSS'],
    containerClassName: 'md:col-span-3',
  },
]

export const STACK = [
  {
    title: 'Frontend',
    desc: 'Building interfaces people actually enjoy using.',
    percent: 92,
    color: '#06b6d4',
    skills: [
      { name: 'React', sub: 'Primary framework' },
      { name: 'Next.js', sub: 'SSR + App Router' },
      { name: 'TailwindCSS', sub: 'Styling' },
      { name: 'Framer Motion', sub: 'Animations' },
      { name: 'TypeScript', sub: 'Type safety' },
    ],
  },
  {
    title: 'Backend',
    desc: 'APIs, bots, and server-side systems.',
    percent: 75,
    color: '#22c55e',
    skills: [
      { name: 'Node.js', sub: 'Runtime' },
      { name: 'Express', sub: 'API server' },
      { name: 'Python', sub: 'Scripts & bots' },
      { name: 'Socket.io', sub: 'Realtime' },
      { name: 'Telethon', sub: 'Telegram bots' },
    ],
  },
  {
    title: 'Database',
    desc: 'Storing and querying data efficiently.',
    percent: 60,
    color: '#eab308',
    skills: [
      { name: 'MongoDB', sub: 'NoSQL' },
      { name: 'Firebase', sub: 'Realtime DB' },
      { name: 'PostgreSQL', sub: 'Relational' },
    ],
  },
  {
    title: 'OSINT & Infra',
    desc: 'Reconnaissance tools and deployment.',
    percent: 80,
    color: '#a855f7',
    skills: [
      { name: 'Python Scrapers', sub: 'Data gathering' },
      { name: 'API Architecture', sub: 'Primary/fallback' },
      { name: 'Vercel', sub: 'Deployment' },
      { name: 'REST APIs', sub: 'Integration' },
    ],
  },
]
